
[[override]]
  name = "gopkg.in/fsnotify.v1"
  source = "https://github.com/fsnotify/fsnotify.git"

[[override]]
  name = "k8s.io/api"
  version = "kubernetes-1.16.0"

[[override]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.16.0"

[[override]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.16.0"

[[override]]
  name = "k8s.io/utils"
  revision = "581e00157fb1a0435d4fac54a52d1ca1e481d60e"

[[constraint]]
  name = "k8s.io/helm"
  version = "v2.7.2"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "v1.4.2"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "v0.0.3"

[prune]
  unused-packages = true
  go-tests = true
  non-go = true
