[[override]]
  name = "k8s.io/api"
  version = "kubernetes-1.14.4"

[[override]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.14.4"

[[override]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.14.4"

[[constraint]]
  name = "k8s.io/helm"
  version = "v2.7.2"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "v1.4.2"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "v0.0.3"

[prune]
  unused-packages = true
  go-tests = true
  non-go = true
